### PR TITLE
V1.5.2

### PR DESCRIPTION
**Pull request by anjakefala**
Update debian repository with VisiData v1.5.2.

Updated devotees.gpg.key with new public key.

@aborruso, please add the new public key and check that this works for you. =)

### CODE REVIEW

**Comment by aborruso** [comment]
Hi,
after

```
wget https://raw.githubusercontent.com/saulpw/deb-vd/master/devotees.gpg.key
apt-key add devotees.gpg.key
sudo apt-get install apt-transport-https
sudo vim /etc/apt/sources.list
    deb [arch=amd64] https://raw.githubusercontent.com/saulpw/deb-vd/master sid main
sudo apt-get update
sudo apt-get install visidata
```

I have `1.2.1-1`.

The way I install `v1.5.2` is (cc @mfortini): 

```
wget https://github.com/saulpw/deb-vd/raw/master/pool/main/v/visidata/visidata_1.5.2-1_all.deb
sudo dpkg -i visidata_1.5.2-1_all.deb
```

Thank you

**Comment by anjakefala** [comment]
VisiData 1.2.1-1 is in `sid` and `buster` =) https://packages.debian.org/buster/visidata

If you have those in your `/etc/apt/sources.list`, it is probably pulling from there first.

**Comment by aborruso** [comment]
@anjakefala I have 9.5 stretch.

This is my list

```
deb https://deb.debian.org/debian stable main contrib non-free
# deb-src https://deb.debian.org/debian stable main

deb https://deb.debian.org/debian stable-updates main
# deb-src https://deb.debian.org/debian stable-updates main

deb http://security.debian.org/debian-security/ stable/updates main
# deb-src http://security.debian.org/debian-security/ stable/updates main

deb https://deb.debian.org/debian stretch-backports main
# deb-src https://deb.debian.org/debian stretch-backports main

deb https://deb.debian.org/debian testing main contrib non-free
# deb-src https://deb.debian.org/debian testing main

deb https://apt.patrickwu.ml/ stable main
# obtain source from https://github.com/wslutilities/wslu
```

If I do

```
wget https://raw.githubusercontent.com/saulpw/deb-vd/master/devotees.gpg.key
apt-key add devotees.gpg.key
sudo apt-get install apt-transport-https
sudo vim /etc/apt/sources.list
    deb [arch=amd64] https://raw.githubusercontent.com/saulpw/deb-vd/master sid main
sudo apt-get update
sudo apt-get install visidata
```

I have `1.2.1-1`. Moreover I have [this issue](https://github.com/saulpw/visidata/issues/243)

**Comment by anjakefala** [comment]
Hm. I wonder if visidata got merged into debian stable.... Or if the repository is not updating, but is caching. That will be interesting to investigate. pip3 does some caching, and it takes me a while to be able to install the newest version.

Can you remind me what your linux setup is? I seem to remember that your main OS is Windows and you use something like WSL, is that correct? I retested on several different computers, and I could not reproduce either of your issues this morning. 😞 

Also, could you please look through your file system to see if you have any lingering previously installed versions of visidata somewhere? And please look into your PATH for me along with where you have 1.5.2-1 installed?

We will figure this out! Sorry for the hiccups. Please continue using 1.5 in the meantime.

**Comment by anjakefala** [comment]
@aborruso (I am not sure if you get notifications for comments on this PR)

**Comment by aborruso** [comment]
Hi @anjakefala 

> Hm. I wonder if visidata got merged into debian stable.... Or if the repository is not updating, but is caching. That will be interesting to investigate. pip3 does some caching, and it takes me a while to be able to install the newest version.

With pip3 I have [this kind](https://github.com/saulpw/visidata/issues/192#issuecomment-452199072) of problem.

> Can you remind me what your linux setup is? I seem to remember that your main OS is Windows and you use something like WSL, is that correct? I retested on several different computers, and I could not reproduce either of your issues this morning. 😞

I have this one https://github.com/WhitewaterFoundry/WLinux

The strange thing is that I do not have [this problem](https://github.com/saulpw/visidata/issues/243) with visidata_1.5-1_all.deb.

> Also, could you please look through your file system to see if you have any lingering previously installed versions of visidata somewhere? And please look into your PATH for me along with where you have 1.5.2-1 installed?

If I run `sudo apt-get remove visidata` and than `which vd` I have `vd not found`.

Than I run `sudo dpkg -i visidata_1.5.2-1_all.deb` and run vd and I have

```
Traceback (most recent call last):
  File "/usr/bin/vd", line 152, in <module>
    main()
  File "/usr/bin/vd", line 52, in main
    vdtui.loadConfigFile('~/.visidatarc', globals())
AttributeError: module 'visidata' has no attribute 'loadConfigFile'
```

If I use visidata_1.5-1_all.deb I have no error.

Thank you

**Comment by anjakefala** [comment]
Okay, I have an experiment I would like you to try.

Install visidata 1.5.2-1 usng the `dpkg` method.

Then look into `/usr/lib/python3/dist-packages` (it may also possibly be in something like `/usr/lib/python3.5/dist-packages`)

Look for a folder `visidata`. 

If you find such a folder, check whether there are `read` and `execute` permissions for users for every file within it. `grep` within that folder and look for `loadConfigFile`.

If at any step you run into problems or are missing the folder completely, here is how you can fix the problem for now: I would try placing all of these: https://github.com/saulpw/visidata/tree/stable/visidata in a `visidata` folder within `/usr/lib/python3/dist-packages` and ensure it has the appropriate permissions.

Also, please check that `/usr/lib/python3/dist-packages` is somehow in your Operating Systems `Path`. 

I agree that it is very confusing that 1.5 works for you while 1.5.2 does not work. =( The error being at that particular location has also been confusing for me.

I have still not been able to reproduce it but I hope with your sleuthing we can maybe find what the problem is. If nothing comes up, I may attempt to rebuild the package.

Thank you for your patience and for humouring me on this! :bowing_woman:

**Comment by anjakefala** [comment]
@aborruso :angel:

**Comment by aborruso** [comment]
Hi @anjakefala.

> Then look into /usr/lib/python3/dist-packages (it may also possibly be in something like /usr/lib/python3.5/dist-packages)

In `/usr/lib/python3/dist-packages` I have (`ls -la ./`)

<details>
 <summary>list</summary>

```
drwxr-xr-x 1 root root   4096 Jan 15 08:20 .
drwxr-xr-x 1 root root   4096 Jan 15 08:19 ..
-rw-r--r-- 1 root root   3592 Jan 13 23:08 aggregators.py
-rw-r--r-- 1 root root   2295 Jan 13 23:08 asyncthread.py
-rw-r--r-- 1 root root  27472 Jan 13 23:08 canvas.py
-rw-r--r-- 1 root root   5336 Jan 13 23:08 clipboard.py
-rw-r--r-- 1 root root  13512 Jan 13 23:08 cmdlog.py
-rw-r--r-- 1 root root    836 Jan 13 23:08 colors.py
-rw-r--r-- 1 root root  30158 Jan 13 23:08 commands.tsv
-rw-r--r-- 1 root root  11388 Jan 13 23:08 data.py
-rw-r--r-- 1 root root   3236 Jan 13 23:08 describe.py
-rw-r--r-- 1 root root    509 Jan 13 23:08 dev.py
-rw-r--r-- 1 root root    944 Jan 13 23:08 diff.py
-rw-r--r-- 1 root root    494 Jan 13 23:08 errors.py
-rw-r--r-- 1 root root   1868 Jan 13 23:08 freeze.py
-rw-r--r-- 1 root root   7169 Jan 13 23:08 freqtbl.py
-rw-r--r-- 1 root root   5668 Jan 13 23:08 graph.py
-rw-r--r-- 1 root root   1616 Jan 13 23:08 __init__.py
-rw-r--r-- 1 root root   7937 Jan 13 23:08 join.py
drwxr-xr-x 1 root root   4096 Jan 15 08:20 loaders
drwxr-xr-x 1 root root   4096 Jan 15 08:20 man
-rw-r--r-- 1 root root   9333 Jan 13 23:08 metasheets.py
-rw-r--r-- 1 root root    448 Jan 13 23:08 motd.py
-rw-r--r-- 1 root root   5410 Jan 13 23:08 movement.py
-rw-r--r-- 1 root root    785 Jan 13 23:08 namedlist.py
-rw-r--r-- 1 root root   5697 Jan 13 23:08 path.py
-rw-r--r-- 1 root root   3835 Jan 13 23:08 pivot.py
-rw-r--r-- 1 root root   4356 Jan 13 23:08 _profile.py
drwxr-xr-x 1 root root   4096 Jan 15 08:20 __pycache__
-rw-r--r-- 1 root root   9073 Jan 13 23:08 pyobj.py
-rw-r--r-- 1 root root   2537 Jan 13 23:08 regex.py
-rw-r--r-- 1 root root    739 Jan 13 23:08 search.py
-rw-r--r-- 1 root root   2215 Jan 13 23:08 selection.py
-rw-r--r-- 1 root root   8769 Jan 13 23:08 shell.py
-rw-r--r-- 1 root root   1999 Jan 13 23:08 slide.py
-rw-r--r-- 1 root root   3186 Jan 13 23:08 tidydata.py
-rw-r--r-- 1 root root    772 Jan 13 23:08 transpose.py
-rw-r--r-- 1 root root   2919 Jan 13 23:08 _types.py
-rw-r--r-- 1 root root    827 Jan 13 23:08 urlcache.py
-rw-r--r-- 1 root root    747 Jan 13 23:08 utils.py
-rw-r--r-- 1 root root 104230 Jan 13 23:08 vdtui.py
-rw-r--r-- 1 root root    351 Jan 13 23:08 vimkeys.py
-rw-r--r-- 1 root root   1157 Jan 13 23:08 zscroll.py
```
</details>
<br>

> If you find such a folder, check whether there are read and execute permissions for users for every file within it. grep within that folder and look for loadConfigFile.

Whit `grep -rni "loadConfigFile" *` I have

```
Binary file __pycache__/vdtui.cpython-36.pyc matches
Binary file __pycache__/vdtui.cpython-37.pyc matches
vdtui.py:2856:def loadConfigFile(fnrc, _globals=None):
```

> Also, please check that /usr/lib/python3/dist-packages is somehow in your Operating Systems Path.

I do not have it, probably because I use miniconda.

Thank you

**Comment by anjakefala** [comment]
Good news @aborruso! All of the code is there.

Bad news....your bin/vd cannot find it. My guess is that is finding another `visidata/` folder somewhere else on your system and that `visidata/` does not have `def loadConfigFile`. In fact, I believe v1.5 does not have it. I think it was added in v1.5.1.

I cannot really help you without having access to your system. =( I think if you can find this residual `visidata/` folder, then everything should work.

**Comment by anjakefala** [comment]
Also, I would confirm that the `visidata/` folder that you `ls -al`d for me has `r-x` permissions for users!

**Comment by aborruso** [comment]
Hi @anjakefala 

> I cannot really help you without having access to your system. =( I think if you can find this residual visidata/ folder, then everything should work.

I have these residual visidata folders:

```
/home/andybandy/.visidata
/home/andybandy/miniconda3/pkgs/visidata-1.3.1-py_0
/home/andybandy/miniconda3/pkgs/visidata-1.4-py_0
/home/andybandy/miniconda3/pkgs/visidata-1.5-py_0
/home/andybandy/miniconda3/pkgs/visidata-1.3.1-py_0/site-packages/visidata
/home/andybandy/miniconda3/pkgs/visidata-1.3.1-py_0/site-packages/visidata-1.3.1-py3.7.egg-info
/home/andybandy/miniconda3/pkgs/visidata-1.4-py_0/site-packages/visidata
/home/andybandy/miniconda3/pkgs/visidata-1.4-py_0/site-packages/visidata-1.4.dist-info
/home/andybandy/miniconda3/pkgs/visidata-1.5-py_0/site-packages/visidata
/home/andybandy/miniconda3/pkgs/visidata-1.5-py_0/site-packages/visidata-1.5.dist-info
/root/.visidata
/usr/local/lib/python3.6/dist-packages/visidata
/usr/local/lib/python3.6/dist-packages/visidata-1.4.dist-info
```

I haver already run `conda remove visidata`.

> Also, I would confirm that the visidata/ folder that you ls -ald for me has r-x permissions for users!

I have `drwxr-xr-x 1 root root   4096 Jan 16 08:54 visidata`

What can I do? To delete some folders?

Thank you

**Comment by anjakefala** [comment]
Ah, yes, please. Or move them to a folder in `/tmp` in the meanwhile if you are nervous about deleting them outright. Please try removing the one in the `/usr/local/lib/python3.6/` folder first.

**Comment by aborruso** [comment]
@anjakefala it works!! Thank you very very very much for your time

**Comment by anjakefala** [comment]
ENJOY! 😊

**Pull request merged**
